module.exports = {
  up: 'CREATE TABLE users (id VARCHAR(50) NOT NULL ,  name TEXT NULL DEFAULT NULL ,  email VARCHAR(50) NOT NULL ,  password TEXT NOT NULL , created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  PRIMARY KEY  (id))',
  down: 'DROP TABLE users',
};
