module.exports = {
    "up": "CREATE TABLE users (id VARCHAR(50) NOT NULL ,  name VARCHAR(50) NULL DEFAULT NULL ,  email VARCHAR(50) NOT NULL ,  password VARCHAR(50) NOT NULL , created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  PRIMARY KEY  (id))",
    "down": "DROP TABLE users"
}